button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_ulic_person
                variables:
                  image: /local/images/person/Jan.jpeg
                  entity_person: person.jan
                  entity_battery: sensor.jan_pixel3_battery_level
                  entity_charging: binary_sensor.jan_pixel3_is_charging
                  entity_time_to_home: sensor.jan_to_home
              - type: custom:button-card
                template: card_ulic_person
                variables:
                  image: /local/images/person/Josh.jpeg
                  entity_battery: sensor.pixel_6_battery_level
                  entity_charging: binary_sensor.pixel_6_is_charging
                  entity_person: person.josh
                  entity_time_to_home: sensor.josh_to_home
                  alignment: right
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: card_light_slider
                entity: light.dining_room_shaded_lamp
              - type: "custom:button-card"
                template: card_light_slider
                entity: light.living_room_floor_lamp
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: card_light
                entity: switch.front_porch
              - type: "custom:button-card"
                template: card_light
                entity: switch.back_porch
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: card_light
                entity: light.christmas_tree
              - type: "custom:button-card"
                template: card_ulic_wled
                entity: light.wled_kitchen1
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity: climate.downstairs
                theme: custom
                card_mod:
                  style:
                    round-slider$: |
                      .bar {
                        transition: none;
                        --round-slider-bar-color: lightgray;
                      }
                    .: |
                      #modes {
                        display: none;
                      }
              - type: custom:button-card
                template: card_ulic_garage_door
                entity: cover.garage_door
                card_mod:
                  style:
                    .: |
                      ha-icon {
                        top: -6px;
                      }
  - title: Media
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: sensor.active_media_players
                state_not: "0"
            card:
              type: custom:button-card
              template: card_title
              name: Now Playing
          # Plex - Personal
          - type: custom:button-card
            template:
              - card_ulic_nowplaying_with_controls
              - nowplaying_no_volume
            variables:
              fallback: media_player.roku
            entity: media_player.plex_home_roku
          - type: custom:button-card
            template: card_ulic_nowplaying_with_controls
            entity: media_player.plex_josh_eriadu_chrome
          - type: custom:button-card
            template: card_ulic_nowplaying_with_controls
            entity: media_player.plex_josh_pixel_6
          - type: custom:button-card
            template:
              - card_ulic_nowplaying_with_controls
              - nowplaying_no_volume
            entity: media_player.plexamp_eriadu
          - type: custom:button-card
            template: card_ulic_nowplaying_with_controls
            entity: media_player.plexamp_josh_pixel_6
          # Plex - Friends & Family
          - type: custom:button-card
            template: card_ulic_nowplaying
            entity: media_player.plex_parents_livingroom_roku
          - type: custom:button-card
            template: card_ulic_nowplaying
            entity: media_player.plex_chaosascends_roku_3
          - type: custom:button-card
            template: card_ulic_nowplaying
            entity: media_player.plex_mickelsons_downstairs_chromecast
          - type: custom:button-card
            template: card_ulic_nowplaying
            entity: media_player.plex_wells_vizio_tv
          - type: custom:button-card
            template: card_ulic_nowplaying
            entity: media_player.plex_carpenters_android_tv
          # Devices
          - type: custom:button-card
            template: card_ulic_nowplaying_with_controls
            entity: media_player.living_room_cc
          - type: custom:button-card
            template: card_ulic_nowplaying_with_controls
            entity: media_player.nesthub1d20
          # Apps
          - type: custom:button-card
            template:
              - card_ulic_nowplaying
              - nowplaying_no_progress
            entity: media_player.spotify_ulic75

          - type: custom:button-card
            template: card_title
            name: Media VPNs
          - type: custom:button-card
            template: card_ulic_vpn
            entity: input_select.roku_vpn_state
  - title: Automations
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_input_boolean
                entity: input_boolean.dusk_automation
                name: Dusk
              - type: custom:button-card
                template: card_input_boolean
                entity: input_boolean.bedtime_automation
                name: Bedtime
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: card_input_boolean
                entity: input_boolean.poker_night
                name: Poker Night
              - type: custom:gap-card
